In [1]:
pip install sdv sdmetrics

Collecting sdv
  Using cached sdv-1.37.0-py3-none-any.whl.metadata (14 kB)
Collecting sdmetrics
  Using cached sdmetrics-0.28.0-py3-none-any.whl.metadata (9.9 kB)
Collecting boto3<2.0.0,>=1.28 (from sdv)
  Downloading boto3-1.43.24-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<2.0.0,>=1.31 (from sdv)
  Downloading botocore-1.43.24-py3-none-any.whl.metadata (5.6 kB)
Collecting cloudpickle>=2.1.0 (from sdv)
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting graphviz>=0.13.2 (from sdv)
  Using cached graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: numpy>=1.24.0 in /home/karl/anaconda3/envs/ECBD/lib/python3.11/site-packages (from sdv) (2.4.6)
Collecting pandas<3,>=1.5.0 (from sdv)
  Using cached pandas-2.3.3-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
Collecting tqdm>=4.29 (from sdv)
  Downloading tqdm-4.68.1-py3-none-any.whl.metadata (57 kB)
Collecting copulas>=0.12.1 (from sdv)
  Using cached copulas-0.14.1-py3-none-any.whl.metadata (9.7 kB)
Collecting ctgan>=0.11.1 (from sdv)
  Using cached ctgan-0.12.1-py3-none-any.whl.metadata (10 kB)
Collecting deepecho>=0.7.0 (from sdv)
  Using cached deepecho-0.8.1-py3-none-any.whl.metadata (11 kB)
Collecting rdt>=1.18.2 (from sdv)
  Using cached rdt-1.21.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: platformdirs>=4.0 in /home/karl/anaconda3/envs/ECBD/lib/python3.11/site-packages (from sdv) (4.9.4)
Requirement already satisfied: pyyaml>=6.0.1 in /home/karl/anaconda3/envs/ECBD/lib/python3.11/site-packages (from sdv) (6.0.3)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2.0.0,>=1.28->sdv)
  Using cached jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.19.0,>=0.18.0 (from boto3<2.0.0,>=1.28->sdv)
  Using cached s3transfer-0.18.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/karl/anaconda3/envs/ECBD/lib/python3.11/site-packages (from botocore<2.0.0,>=1.31->sdv) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /home/karl/anaconda3/envs/ECBD/lib/python3.11/site-packages (from botocore<2.0.0,>=1.31->sdv) (2.7.0)
Collecting pytz>=2020.1 (from pandas<3,>=1.5.0->sdv)
  Using cached pytz-2026.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas<3,>=1.5.0->sdv)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /home/karl/anaconda3/envs/ECBD/lib/python3.11/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.31->sdv) (1.17.0)
Collecting scikit-learn>=1.1.3 (from sdmetrics)
  Using cached scikit_learn-1.9.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Collecting scipy>=1.9.2 (from sdmetrics)
  Using cached scipy-1.17.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting plotly>=5.19.0 (from sdmetrics)
  Using cached plotly-6.8.0-py3-none-any.whl.metadata (9.0 kB)
Collecting torch>=2.0.0 (from ctgan>=0.11.1->sdv)
  Using cached torch-2.12.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (31 kB)
Collecting narwhals>=1.15.1 (from plotly>=5.19.0->sdmetrics)
  Downloading narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: packaging in /home/karl/anaconda3/envs/ECBD/lib/python3.11/site-packages (from plotly>=5.19.0->sdmetrics) (26.0)
Requirement already satisfied: Faker!=37.11.0,>=17 in /home/karl/anaconda3/envs/ECBD/lib/python3.11/site-packages (from rdt>=1.18.2->sdv) (40.21.0)
Collecting joblib>=1.4.0 (from scikit-learn>=1.1.3->sdmetrics)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn>=1.1.3->sdmetrics)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting filelock (from torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached filelock-3.29.1-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: typing-extensions>=4.10.0 in /home/karl/anaconda3/envs/ECBD/lib/python3.11/site-packages (from torch>=2.0.0->ctgan>=0.11.1->sdv) (4.15.0)
Collecting setuptools<82 (from torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: jinja2 in /home/karl/anaconda3/envs/ECBD/lib/python3.11/site-packages (from torch>=2.0.0->ctgan>=0.11.1->sdv) (3.1.6)
Collecting fsspec>=0.8.5 (from torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached fsspec-2026.4.0-py3-none-any.whl.metadata (10 kB)
Collecting cuda-toolkit==13.0.2 (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached cuda_toolkit-13.0.2-py2.py3-none-any.whl.metadata (9.4 kB)
Collecting nvidia-cublas<=13.1.1.3,>=13.1.0.3 (from torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached nvidia_cublas-13.1.1.3-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting cuda-bindings<14,>=13.0.3 (from torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached cuda_bindings-13.3.1-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.5 kB)
Collecting nvidia-cudnn-cu13==9.20.0.48 (from torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached nvidia_cudnn_cu13-9.20.0.48-py3-none-manylinux_2_27_x86_64.whl.metadata (1.9 kB)
Collecting nvidia-cusparselt-cu13==0.8.1 (from torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_x86_64.whl.metadata (12 kB)
Collecting nvidia-nccl-cu13==2.29.7 (from torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached nvidia_nccl_cu13-2.29.7-py3-none-manylinux_2_18_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvshmem-cu13==3.4.5 (from torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting triton==3.7.0 (from torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached triton-3.7.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime==13.0.96.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft==12.0.0.61.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cufile==1.15.1.6.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti==13.0.85.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand==10.4.0.35.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver==12.0.4.66.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse==12.6.3.3.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink==13.0.88.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached nvidia_nvjitlink-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-nvrtc==13.0.88.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-nvtx==13.0.85.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (1.8 kB)
Collecting cuda-pathfinder>=1.4.2 (from cuda-bindings<14,>=13.0.3->torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached cuda_pathfinder-1.5.5-py3-none-any.whl.metadata (1.9 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=2.0.0->ctgan>=0.11.1->sdv)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /home/karl/anaconda3/envs/ECBD/lib/python3.11/site-packages (from jinja2->torch>=2.0.0->ctgan>=0.11.1->sdv) (3.0.2)
Using cached sdv-1.37.0-py3-none-any.whl (206 kB)
Downloading boto3-1.43.24-py3-none-any.whl (140 kB)
Downloading botocore-1.43.24-py3-none-any.whl (15.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.2/15.2 MB 1.0 MB/s  0:00:14m0:00:0100:010m
Using cached jmespath-1.1.0-py3-none-any.whl (20 kB)
Using cached pandas-2.3.3-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.8 MB)
Using cached s3transfer-0.18.0-py3-none-any.whl (88 kB)
Using cached sdmetrics-0.28.0-py3-none-any.whl (202 kB)
Using cached cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Using cached copulas-0.14.1-py3-none-any.whl (52 kB)
Using cached ctgan-0.12.1-py3-none-any.whl (25 kB)
Using cached deepecho-0.8.1-py3-none-any.whl (28 kB)
Using cached graphviz-0.21-py3-none-any.whl (47 kB)
Using cached plotly-6.8.0-py3-none-any.whl (9.9 MB)
Downloading narwhals-2.22.1-py3-none-any.whl (454 kB)
Using cached pytz-2026.2-py2.py3-none-any.whl (510 kB)
Using cached rdt-1.21.0-py3-none-any.whl (74 kB)
Using cached scikit_learn-1.9.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (9.3 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached scipy-1.17.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.3 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading torch-2.12.0-cp311-cp311-manylinux_2_28_x86_64.whl (532.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 532.2/532.2 MB 715.1 kB/s  0:10:550:00:0100:17
Downloading cuda_toolkit-13.0.2-py2.py3-none-any.whl (2.4 kB)
Downloading nvidia_cudnn_cu13-9.20.0.48-py3-none-manylinux_2_27_x86_64.whl (366.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.2/366.2 MB 877.2 kB/s  0:06:440:00:010:09m
Downloading nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_x86_64.whl (170.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.1/170.1 MB 618.6 kB/s  0:03:290:00:0100:11
Downloading nvidia_nccl_cu13-2.29.7-py3-none-manylinux_2_18_x86_64.whl (206.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.0/206.0 MB 963.4 kB/s  0:03:500:00:0100:08
Downloading nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (60.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 MB 856.7 kB/s  0:01:13m0:00:0100:03
Downloading triton-3.7.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (201.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.4/201.4 MB 1.1 MB/s  0:03:32m0:00:01m00:06
Downloading cuda_bindings-13.3.1-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (6.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 931.2 kB/s  0:00:07 eta 0:00:02
Downloading nvidia_cublas-13.1.1.3-py3-none-manylinux_2_27_x86_64.whl (423.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 MB 956.0 kB/s  0:08:180:00:0100:15
Downloading nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 1.0 MB/s  0:00:10m0:00:0100:01m
Downloading nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (90.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 MB 848.9 kB/s  0:01:50m0:00:0100:03
Downloading nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 1.1 MB/s  0:00:02 eta 0:00:01
Downloading nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (214.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.1/214.1 MB 745.0 kB/s  0:04:350:00:0100:09
Downloading nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 744.1 kB/s  0:00:01 eta 0:00:01
Downloading nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl (59.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 MB 1.1 MB/s  0:01:10m0:00:0100:020m
Downloading nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl (200.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.9/200.9 MB 862.5 kB/s  0:05:180:00:0100:07
Downloading nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (145.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.9/145.9 MB 959.9 kB/s  0:02:360:00:0100:04
Downloading nvidia_nvjitlink-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (40.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.7/40.7 MB 907.9 kB/s  0:00:54m0:00:0100:02
Downloading nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (148 kB)
Downloading setuptools-81.0.0-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 792.0 kB/s  0:00:01 eta 0:00:01
Downloading cuda_pathfinder-1.5.5-py3-none-any.whl (51 kB)
Downloading fsspec-2026.4.0-py3-none-any.whl (203 kB)
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 825.5 kB/s  0:00:02 eta 0:00:01
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 889.5 kB/s  0:00:07 eta 0:00:01
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 938.7 kB/s  0:00:00m-:--:--
Downloading tqdm-4.68.1-py3-none-any.whl (78 kB)
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Downloading filelock-3.29.1-py3-none-any.whl (40 kB)
Installing collected packages: pytz, nvidia-cusparselt-cu13, mpmath, cuda-toolkit, tzdata, triton, tqdm, threadpoolctl, sympy, setuptools, scipy, nvidia-nvtx, nvidia-nvshmem-cu13, nvidia-nvjitlink, nvidia-nccl-cu13, nvidia-curand, nvidia-cufile, nvidia-cuda-runtime, nvidia-cuda-nvrtc, nvidia-cuda-cupti, networkx, narwhals, joblib, jmespath, graphviz, fsspec, filelock, cuda-pathfinder, cloudpickle, scikit-learn, plotly, pandas, nvidia-cusparse, nvidia-cufft, nvidia-cublas, cuda-bindings, botocore, s3transfer, rdt, nvidia-cusolver, nvidia-cudnn-cu13, copulas, sdmetrics, boto3, torch, deepecho, ctgan, sdv
  Attempting uninstall: setuptools━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/48 [sympy]]t-cu13]
    Found existing installation: setuptools 82.0.1━━━━━━━━━━━━  8/48 [sympy]
    Uninstalling setuptools-82.0.1:━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/48 [sympy]
      Successfully uninstalled setuptools-82.0.1━━━━━━━━━━━━━━━━━━  9/48 [setuptools]
  Attempting uninstall: pandas━━━╺━━━━━━━━━━━━━━ 30/48 [plotly]learn]upti]3]
    Found existing installation: pandas 3.0.390m━━━━━━━━━━━━━━ 30/48 [plotly]
    Uninstalling pandas-3.0.3:━━━╸━━━━━━━━━━━━━━ 31/48 [pandas]
      Successfully uninstalled pandas-3.0.3━━━━━━━━━━━━━━ 31/48 [pandas]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48/48 [sdv][0m [sdv][0m [torch]s]udnn-cu13]
Successfully installed boto3-1.43.24 botocore-1.43.24 cloudpickle-3.1.2 copulas-0.14.1 ctgan-0.12.1 cuda-bindings-13.3.1 cuda-pathfinder-1.5.5 cuda-toolkit-13.0.2 deepecho-0.8.1 filelock-3.29.1 fsspec-2026.4.0 graphviz-0.21 jmespath-1.1.0 joblib-1.5.3 mpmath-1.3.0 narwhals-2.22.1 networkx-3.6.1 nvidia-cublas-13.1.1.3 nvidia-cuda-cupti-13.0.85 nvidia-cuda-nvrtc-13.0.88 nvidia-cuda-runtime-13.0.96 nvidia-cudnn-cu13-9.20.0.48 nvidia-cufft-12.0.0.61 nvidia-cufile-1.15.1.6 nvidia-curand-10.4.0.35 nvidia-cusolver-12.0.4.66 nvidia-cusparse-12.6.3.3 nvidia-cusparselt-cu13-0.8.1 nvidia-nccl-cu13-2.29.7 nvidia-nvjitlink-13.0.88 nvidia-nvshmem-cu13-3.4.5 nvidia-nvtx-13.0.85 pandas-2.3.3 plotly-6.8.0 pytz-2026.2 rdt-1.21.0 s3transfer-0.18.0 scikit-learn-1.9.0 scipy-1.17.1 sdmetrics-0.28.0 sdv-1.37.0 setuptools-81.0.0 sympy-1.14.0 threadpoolctl-3.6.0 torch-2.12.0 tqdm-4.68.1 triton-3.7.0 tzdata-2026.2
Note: you may need to restart the kernel to use updated packages.

# Libreria SDV 
*Autor: Carlos*
*Fecha: 04 junio*

In [1]:
import pandas as pd 
import numpy as np 
import random

In [2]:
import sdv # Generar datos sintéticos
import sdmetrics # Evaluar la calidad de los datos
from sdv.metadata import SingleTableMetadata
from sdv.single_table import GaussianCopulaSynthesizer

In [3]:
from sdmetrics.reports.single_table import QualityReport

In [4]:
print("SDV", sdv.__version__)

SDV 1.37.0

In [5]:
# Creamos un dataset (original) que servira como fuente para crear los datos sintéticos
dfClient = pd.DataFrame({
    "cliente_id": [1,2,3,4,5,6,7,8,9,10],
    "edad": [23,33,43,28,53,56,43,56,65,40],
    "ingreso_mensual": [25000, 15000, 20000, 10000, 5000, 17000, 30000, 12000, 35000, 7500],
    "ciudad": ["Cordoba", "Veracruz", "Paso del Macho", "Amatlan", "Fortin", "Cuitlahuac", "Yanga", "Orizaba", "Cuitlahuac", "Potrero"]
})

In [6]:
dfClient.head()

   cliente_id  edad  ingreso_mensual          ciudad
0           1    23            25000         Cordoba
1           2    33            15000        Veracruz
2           3    43            20000  Paso del Macho
3           4    28            10000         Amatlan
4           5    53             5000          Fortin

In [8]:
# Definir la metadata
metadata = SingleTableMetadata()

In [9]:
metadata.detect_from_dataframe(
    data = dfClient
)

In [11]:
metadata.to_dict()

{'columns': {'cliente_id': {'sdtype': 'id'},
  'edad': {'sdtype': 'numerical'},
  'ingreso_mensual': {'sdtype': 'numerical'},
  'ciudad': {'sdtype': 'categorical'}},
 'primary_key': 'cliente_id',
 'METADATA_SPEC_VERSION': 'SINGLE_TABLE_V1'}

In [12]:
# Guardar la metadata en JSON
metadata.save_to_json(
    "dfClient_metadata.json"
)

In [13]:
# Entrenar el modelo para grenerar los datos sintéticos
synthesizer = GaussianCopulaSynthesizer(
    metadata
)

/home/karl/anaconda3/envs/ECBD/lib/python3.11/site-packages/sdv/single_table/base.py:182: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)

In [14]:
# Entrenamiento
synthesizer.fit(
    dfClient
)

In [15]:
# Generar los datos sintéticos
clientes_sinteticos = synthesizer.sample(
    num_rows = 100
)

In [16]:
clientes_sinteticos.head()

   cliente_id  edad  ingreso_mensual    ciudad
0    16169768    59            14778    Fortin
1     4918803    38            32141   Cordoba
2     1900081    36            19072  Veracruz
3      531516    30            28659  Veracruz
4    10211768    51            28681    Fortin

In [17]:
clientes_sinteticos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   cliente_id       100 non-null    int64
 1   edad             100 non-null    int64
 2   ingreso_mensual  100 non-null    int64
 3   ciudad           100 non-null    object
dtypes: int64(3), object(1)
memory usage: 3.3+ KB

In [18]:
clientes_sinteticos.describe( include = "all" )

          cliente_id        edad  ingreso_mensual   ciudad
count   1.000000e+02  100.000000       100.000000      100
unique           NaN         NaN              NaN        9
top              NaN         NaN              NaN  Cordoba
freq             NaN         NaN              NaN       61
mean    8.532170e+06   42.900000     21678.150000      NaN
std     4.687773e+06   11.846237      8671.615725      NaN
min     4.660500e+04   28.000000      6185.000000      NaN
25%     5.008268e+06   33.000000     14356.750000      NaN
50%     8.656048e+06   41.000000     21358.500000      NaN
75%     1.256688e+07   52.500000     28983.000000      NaN
max     1.661551e+07   65.000000     34944.000000      NaN

In [19]:
# Crear un dataframe contaminado
dfContaminado = clientes_sinteticos.copy()

In [20]:
# Colocar edades imposibles
indices = random.sample(list(dfContaminado.index), 5)

In [21]:
dfContaminado.loc[indices, "edad" ] = -5

In [22]:
# Introducir valores nulos 
duplicados = dfContaminado.sample(10, random_state = 42)

In [23]:
dfContaminado = pd.concat([dfContaminado, duplicados], ignore_index = True )

In [24]:
# Verificar valores nulos
dfContaminado.duplicated().sum()

np.int64(10)

In [25]:
dfContaminado.describe( include = "all" )

          cliente_id        edad  ingreso_mensual   ciudad
count   1.100000e+02  110.000000       110.000000      110
unique           NaN         NaN              NaN        9
top              NaN         NaN              NaN  Cordoba
freq             NaN         NaN              NaN       70
mean    8.614045e+06   38.954545     21341.318182      NaN
std     4.775996e+06   16.167351      8625.934017      NaN
min     4.660500e+04   -5.000000      6185.000000      NaN
25%     4.948624e+06   30.000000     14254.250000      NaN
50%     8.956428e+06   38.500000     20550.500000      NaN
75%     1.274153e+07   50.750000     28813.750000      NaN
max     1.661551e+07   65.000000     34944.000000      NaN

In [26]:
# Generar el reporte
reporte = QualityReport()

In [27]:
reporte.generate(
    real_data = dfClient,
    synthetic_data = clientes_sinteticos,
    metadata = metadata.to_dict()
)

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 4/4 [00:00<00:00, 408.17it/s]|
Column Shapes Score: 66.33%

(2/2) Evaluating Column Pair Trends: |██████████| 6/6 [00:00<00:00, 136.93it/s]|
Column Pair Trends Score: 8.5%

Overall Score (Average): 37.42%

In [28]:
reporte.generate(
    real_data = dfClient,
    synthetic_data = dfContaminado,
    metadata = metadata.to_dict()
)

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 4/4 [00:00<00:00, 365.80it/s]|
Column Shapes Score: 64.55%

(2/2) Evaluating Column Pair Trends: |██████████| 6/6 [00:00<00:00, 137.02it/s]|
Column Pair Trends Score: 3.18%

Overall Score (Average): 33.86%