# Lab 14 - Algoritmo KNN 
## Objetivo 
Implementar el algoritmo K-Nearest Neighbors(KNN) para clasificar especies de flores utilizando el dataset Wine, aplicando el flujo completo de un modelo supervisado: preparación de datos, entrenamiento, predicción y evaluación del modelo.

In [1]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [23]:
## Descargar el datasetde Wine
wine = load_wine(as_frame=True)

print(wine.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

:Number of Instances: 178
:Number of Attributes: 13 numeric, predictive attributes and the class
:Attribute Information:
    - Alcohol
    - Malic acid
    - Ash
    - Alcalinity of ash
    - Magnesium
    - Total phenols
    - Flavanoids
    - Nonflavanoid phenols
    - Proanthocyanins
    - Color intensity
    - Hue
    - OD280/OD315 of diluted wines
    - Proline
    - class:
        - class_0
        - class_1
        - class_2

:Summary Statistics:

============================= ==== ===== ======= =====
                                Min   Max   Mean     SD
============================= ==== ===== ======= =====
Alcohol:                      11.0  14.8    13.0   0.8
Malic Acid:                   0.74  5.80    2.34  1.12
Ash:                          1.36  3.23    2.36  0.27
Alcalinity of Ash:            10.6  30.0    19.5   3.3
Magnesium:                    70.0 162.0    99.7  14.3
Total Phenols:                0.98  3.88    2.29  0.63
Flavanoids:                   0.34  5.08    2.03  1.00
Nonflavanoid Phenols:         0.13  0.66    0.36  0.12
Proanthocyanins:              0.41  3.58    1.59  0.57
Colour Intensity:              1.3  13.0     5.1   2.3
Hue:                          0.48  1.71    0.96  0.23
OD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71
Proline:                       278  1680     746   315
============================= ==== ===== ======= =====

:Missing Attribute Values: None
:Class Distribution: class_0 (59), class_1 (71), class_2 (48)
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

This is a copy of UCI ML Wine recognition datasets.
https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data

The data is the results of a chemical analysis of wines grown in the same
region in Italy by three different cultivators. There are thirteen different
measurements taken for different constituents found in the three types of
wine.

Original Owners:

Forina, M. et al, PARVUS -
An Extendable Package of Programs for Data Exploration, Classification and Correlation.
Institute of Pharmaceutical and Food Analysis and Technologies,
Via Brigata Salerno, 16147 Genoa, Italy.

Citation:

Lichman, M. (2013). UCI Machine Learning Repository
[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,
School of Information and Computer Science.

.. dropdown:: References

    (1) S. Aeberhard, D. Coomans and O. de Vel,
    Comparison of Classifiers in High Dimensional Settings,
    Tech. Rep. no. 92-02, (1992), Dept. of Computer Science and Dept. of
    Mathematics and Statistics, James Cook University of North Queensland.
    (Also submitted to Technometrics).

    The data was used with many others for comparing various
    classifiers. The classes are separable, though only RDA
    has achieved 100% correct classification.
    (RDA : 100%, QDA 99.4%, LDA 98.9%, 1NN 96.1% (z-transformed data))
    (All results using the leave-one-out technique)

    (2) S. Aeberhard, D. Coomans and O. de Vel,
    "THE CLASSIFICATION PERFORMANCE OF RDA"
    Tech. Rep. no. 92-01, (1992), Dept. of Computer Science and Dept. of
    Mathematics and Statistics, James Cook University of North Queensland.
    (Also submitted to Journal of Chemometrics).

## Crear el DataFrame

In [3]:
dfWine = wine.frame

dfWine.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

## Explorar el dataset

In [4]:
dfWine.shape

(178, 14)

In [5]:
dfWine.columns

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline', 'target'],
      dtype='object')

In [6]:
dfWine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
 13  target                        178 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 19.6 KB

In [7]:
dfWine.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,0.938202
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,0.775035
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,0.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,0.000000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,1.000000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,2.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,2.000000

In [8]:
dfWine.isnull().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
target                          0
dtype: int64

## Modificar el nombre de la columna

In [9]:
dfWine.rename(columns={"target":"clase"}, inplace=True)

X = dfWine.drop("clase", axis=1)
y = dfWine["clase"]

## Variables predictoras y objetivo

In [10]:
X = dfWine.drop(columns=["clase"])

print("Variables predictoras")
print(X.columns)

Variables predictoras
Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline'],
      dtype='object')

In [11]:
y = dfWine["clase"]

print("Variable objetivo")
print(y.name)

Variable objetivo
clase

## Comenzar con la separación de datos de entrenamiento y de prueba

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [13]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (142, 13)
X_test: (36, 13)
y_train: (142,)
y_test: (36,)

## Realizar el escalado de los datos

In [14]:
scaler = StandardScaler()

X_train_escalado = scaler.fit_transform(X_train)
X_test_escalado = scaler.transform(X_test)

In [15]:
print("Datos originales")
print(X_train.head())

print("\nDatos escalados")
print(X_train_escalado[:5])

Datos originales
     alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
36     13.28        1.64  2.84               15.5      110.0           2.60
30     13.73        1.50  2.70               22.5      101.0           3.00
26     13.39        1.77  2.62               16.1       93.0           2.85
12     13.75        1.73  2.41               16.0       89.0           2.60
148    13.32        3.24  2.38               21.5       92.0           1.93

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
36         2.68                  0.34             1.36             4.60  1.09
30         3.25                  0.29             2.38             5.70  1.19
26         2.94                  0.34             1.45             4.80  0.92
12         2.76                  0.29             1.81             5.60  1.15
148        0.76                  0.45             1.25             8.42  0.55

     od280/od315_of_diluted_wines  proline
36                           2.78    880.0
30                           2.71   1285.0
26                           3.22   1195.0
12                           2.90   1320.0
148                          1.62    650.0

Datos escalados
[[ 0.38580089 -0.63787118  1.77666817 -1.22453161  0.69643032  0.52686525
   0.73229212 -0.1695489  -0.41578344 -0.16746725  0.62437819  0.2529082
   0.46772474]
 [ 0.94851892 -0.76544542  1.25317383  0.85328406  0.09178497  1.17279546
   1.33318146 -0.59045701  1.34974202  0.30530313  1.06715537  0.15104809
   1.81576773]
 [ 0.52335419 -0.51940939  0.9540342  -1.04643312 -0.44567755  0.93057163
   1.006382   -0.1695489  -0.26000178 -0.081509   -0.12834302  0.89317174
   1.51620262]
 [ 0.97352861 -0.55585917  0.16879269 -1.0761162  -0.71440882  0.52686525
   0.81662747 -0.59045701  0.36312485  0.262324    0.8900445   0.42752553
   1.93226527]
 [ 0.43582027  0.82012009  0.05661533  0.55645325 -0.51286037 -0.55506784
  -1.29175618  0.75644894 -0.60618325  1.47433535 -1.76661859 -1.43505932
  -0.29783054]]

## Comenzamos con la creación del modelo KNN

In [16]:
modelo = KNeighborsClassifier(n_neighbors=3)

## Realizamos el entrenamiento

In [17]:
modelo.fit(
    X_train_escalado,
    y_train
)

KNeighborsClassifier(n_neighbors=3)

## Hacemos predicciones

In [18]:
prediccion = modelo.predict(X_test_escalado)

print(prediccion[:10])

[0 2 0 0 1 0 0 1 1 2]

In [19]:
comparacion = pd.DataFrame({
    "Clase real": y_test.values,
    "Clase predicha": prediccion
})

comparacion.head(15)

    Clase real  Clase predicha
0            0               0
1            2               2
2            0               0
3            1               0
4            1               1
5            0               0
6            0               0
7            1               1
8            1               1
9            2               2
10           1               1
11           2               2
12           0               0
13           2               2
14           0               0

## Se evalúa la exactitud del modelo

In [20]:
accuracy = accuracy_score(
    y_test,
    prediccion
)

print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.9722

## Aplicamos la matriz de confusión

In [21]:
cm = confusion_matrix(
    y_test,
    prediccion
)

cm_df = pd.DataFrame(
    cm,
    index=modelo.classes_,
    columns=modelo.classes_
)

cm_df

    0   1   2
0  12   0   0
1   1  13   0
2   0   0  10

## Aquí definiremos el reporte de clasificación

In [22]:
print(
    classification_report(
        y_test,
        prediccion
    )
)

              precision    recall  f1-score   support

           0       0.92      1.00      0.96        12
           1       1.00      0.93      0.96        14
           2       1.00      1.00      1.00        10

    accuracy                           0.97        36
   macro avg       0.97      0.98      0.97        36
weighted avg       0.97      0.97      0.97        36

# Conclusiones
## Limpieza de datos
Se verificó la existencia de valores nulos mediante isnull().sum().
El conjunto de datos Wine no contiene valores faltantes, por lo que no fue necesario eliminar registros ni realizar imputaciones.
La variable objetivo fue renombrada de target a clase para facilitar su interpretación y posteriormente se reemplazaron los valores numéricos por nombres descriptivos.
Debido a que el algoritmo KNN utiliza la distancia entre observaciones, fue necesario aplicar StandardScaler para estandarizar todas las variables y evitar que aquellas con mayor magnitud influyeran más en la clasificación.
## Hallazgos
El modelo KNN fue entrenado utilizando el 80 % de los datos y evaluado con el 20 % restante.
Se utilizó un valor de k = 3, suficiente para obtener una buena clasificación del conjunto Wine.
La estandarización permitió que todas las características tuvieran la misma importancia durante el cálculo de distancias.
La matriz de confusión mostró cuántas muestras fueron clasificadas correctamente y cuáles presentaron errores.